"""+Courses

Revision ID: 4efde52af57a
Revises: a8e5252822d4
Create Date: 2025-02-20 00:03:02.301556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4efde52af57a'
down_revision: Union[str, None] = 'a8e5252822d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('teacher_name', sa.String(), nullable=False),
    sa.Column('special_course_notes', sa.String(), nullable=True),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_name')
    )
    op.drop_column('majors', 'count_students')
    op.add_column('students', sa.Column('course_id', sa.Integer(), nullable=True))
    op.drop_constraint('students_major_id_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'courses', ['course_id'], ['id'])
    op.drop_column('students', 'major_id')
    op.drop_column('students', 'course')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('course', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('major_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_major_id_fkey', 'students', 'majors', ['major_id'], ['id'])
    op.drop_column('students', 'course_id')
    op.add_column('majors', sa.Column('count_students', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_table('courses')
    # ### end Alembic commands ###
